using System.Collections.Generic;
using System.Runtime.InteropServices.WindowsRuntime;

namespace SpsLogic
{
    /// <summary>
    /// Test-only finder that returns many long steam.exe candidates for SteamExePathDialog layout checks.
    /// </summary>
    public sealed class FindSteamExeServiceDialogTest : IFindSteamExeService
    {
        private const int CandidateCount = 48;

        /// <inheritdoc />
        public FindSteamExeResult Find()
        {
            return new FindSteamExeResult(new SteamExeCandidate[0], new string[0]);
            var candidates = new List<SteamExeCandidate>();
            for (int index = 0; index < CandidateCount; index++)
            {
                candidates.Add(new SteamExeCandidate(
                    CreateLongPath(index),
                    CreateLongSource(index),
                    90000 + index));
            }

            string[] messages =
            {
                "Generated fake steam.exe candidates for SteamExePathDialog layout testing.",
                "Candidate count: " + candidates.Count,
                "The returned paths are intentionally long and are not guaranteed to exist."
            };

            return new FindSteamExeResult(candidates.ToArray(), messages);
        }

        private static string CreateLongPath(int index)
        {
            int group = index % 6;
            return string.Format(
                @"C:\Program Files (x86)\Steam\steamapps\compatdata\SteamP2PScannerDialogLayoutTest\VeryLongCandidateGroup_{0:00}\UserSelectedOrDetectedInstallLocation_WithExtraLongFolderName_ForHorizontalOverflowTesting\NestedSteamRuntimeFolder_{1:00}\AnotherDeepDirectoryNameThatShouldRemainReadableWhenTheDialogIsNarrow\steam.exe",
                group,
                index);
        }

        private static string CreateLongSource(int index)
        {
            switch (index % 4)
            {
                case 0:
                    return "running process PID " + (90000 + index) + " from QueryFullProcessImageName with intentionally verbose diagnostic source text";
                case 1:
                    return @"registry: CurrentUser(Default)\Software\Valve\Steam\SteamExe with intentionally verbose source label";
                case 2:
                    return @"registry: LocalMachine(Registry32)\SOFTWARE\WOW6432Node\Valve\Steam\InstallPath with intentionally verbose source label";
                default:
                    return @"manual test seed generated by FindSteamExeServiceDialogTest to check long source cell clipping";
            }
        }
    }
}
